name: deploy_frontend
# Deploys when push is made from frontend folder

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: login with azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name azureresumenishtweb -d '$web' -s frontend/ --overwrite
      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()